# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/DistancesCarRemoteControler.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 806)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connectionWidget = QtWidgets.QWidget(self.centralwidget)
        self.connectionWidget.setObjectName("connectionWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.connectionWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connectionStateLabel = QtWidgets.QLabel(self.connectionWidget)
        self.connectionStateLabel.setObjectName("connectionStateLabel")
        self.horizontalLayout.addWidget(self.connectionStateLabel)
        self.connectionPushButton = QtWidgets.QPushButton(self.connectionWidget)
        self.connectionPushButton.setObjectName("connectionPushButton")
        self.horizontalLayout.addWidget(self.connectionPushButton)
        self.verticalLayout.addWidget(self.connectionWidget)
        self.stateGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.stateGroupBox.setEnabled(False)
        self.stateGroupBox.setObjectName("stateGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.stateGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.temperatureLcdNumber = QtWidgets.QLCDNumber(self.stateGroupBox)
        self.temperatureLcdNumber.setObjectName("temperatureLcdNumber")
        self.gridLayout_5.addWidget(self.temperatureLcdNumber, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.distancesLabel = QtWidgets.QLabel(self.stateGroupBox)
        self.distancesLabel.setObjectName("distancesLabel")
        self.horizontalLayout_3.addWidget(self.distancesLabel)
        self.distancesLineEdit = QtWidgets.QLineEdit(self.stateGroupBox)
        self.distancesLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.distancesLineEdit.setReadOnly(True)
        self.distancesLineEdit.setObjectName("distancesLineEdit")
        self.horizontalLayout_3.addWidget(self.distancesLineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 4, 0, 1, 2)
        self.dataCountLabel = QtWidgets.QLabel(self.stateGroupBox)
        self.dataCountLabel.setObjectName("dataCountLabel")
        self.gridLayout_5.addWidget(self.dataCountLabel, 2, 0, 1, 1)
        self.temperatureLabel = QtWidgets.QLabel(self.stateGroupBox)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.gridLayout_5.addWidget(self.temperatureLabel, 1, 0, 1, 1)
        self.dataCountLcdNumber = QtWidgets.QLCDNumber(self.stateGroupBox)
        self.dataCountLcdNumber.setObjectName("dataCountLcdNumber")
        self.gridLayout_5.addWidget(self.dataCountLcdNumber, 2, 1, 1, 1)
        self.directionLabel = QtWidgets.QLabel(self.stateGroupBox)
        self.directionLabel.setObjectName("directionLabel")
        self.gridLayout_5.addWidget(self.directionLabel, 3, 0, 1, 1)
        self.directionLineEdit = QtWidgets.QLineEdit(self.stateGroupBox)
        self.directionLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.directionLineEdit.setReadOnly(True)
        self.directionLineEdit.setObjectName("directionLineEdit")
        self.gridLayout_5.addWidget(self.directionLineEdit, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.stateGroupBox)
        self.navigationGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.navigationGroupBox.setEnabled(False)
        self.navigationGroupBox.setObjectName("navigationGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.navigationGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enableCapturePushButton = QtWidgets.QPushButton(self.navigationGroupBox)
        self.enableCapturePushButton.setCheckable(True)
        self.enableCapturePushButton.setObjectName("enableCapturePushButton")
        self.horizontalLayout_2.addWidget(self.enableCapturePushButton)
        self.navigationPushButton = QtWidgets.QPushButton(self.navigationGroupBox)
        self.navigationPushButton.setCheckable(True)
        self.navigationPushButton.setObjectName("navigationPushButton")
        self.horizontalLayout_2.addWidget(self.navigationPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.navigationGroupBox)
        self.controlGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.controlGroupBox.setEnabled(False)
        self.controlGroupBox.setObjectName("controlGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.controlGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.enginesPowerLabel = QtWidgets.QLabel(self.controlGroupBox)
        self.enginesPowerLabel.setObjectName("enginesPowerLabel")
        self.gridLayout_4.addWidget(self.enginesPowerLabel, 0, 0, 1, 1)
        self.enginesPowerSlider = QtWidgets.QSlider(self.controlGroupBox)
        self.enginesPowerSlider.setMaximum(255)
        self.enginesPowerSlider.setPageStep(25)
        self.enginesPowerSlider.setProperty("value", 127)
        self.enginesPowerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.enginesPowerSlider.setObjectName("enginesPowerSlider")
        self.gridLayout_4.addWidget(self.enginesPowerSlider, 0, 1, 1, 1)
        self.enginesPowerlcdNumber = QtWidgets.QLCDNumber(self.controlGroupBox)
        self.enginesPowerlcdNumber.setProperty("value", 127.0)
        self.enginesPowerlcdNumber.setObjectName("enginesPowerlcdNumber")
        self.gridLayout_4.addWidget(self.enginesPowerlcdNumber, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.forwardPushButton = QtWidgets.QPushButton(self.controlGroupBox)
        self.forwardPushButton.setObjectName("forwardPushButton")
        self.gridLayout.addWidget(self.forwardPushButton, 0, 1, 1, 1)
        self.backwardPushButton = QtWidgets.QPushButton(self.controlGroupBox)
        self.backwardPushButton.setObjectName("backwardPushButton")
        self.gridLayout.addWidget(self.backwardPushButton, 2, 1, 1, 1)
        self.rightPushButton = QtWidgets.QPushButton(self.controlGroupBox)
        self.rightPushButton.setObjectName("rightPushButton")
        self.gridLayout.addWidget(self.rightPushButton, 1, 2, 1, 1)
        self.leftPushButton = QtWidgets.QPushButton(self.controlGroupBox)
        self.leftPushButton.setObjectName("leftPushButton")
        self.gridLayout.addWidget(self.leftPushButton, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 3)
        self.keyboardControlTextBrowser = QtWidgets.QTextBrowser(self.controlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyboardControlTextBrowser.sizePolicy().hasHeightForWidth())
        self.keyboardControlTextBrowser.setSizePolicy(sizePolicy)
        self.keyboardControlTextBrowser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.keyboardControlTextBrowser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.keyboardControlTextBrowser.setObjectName("keyboardControlTextBrowser")
        self.gridLayout_4.addWidget(self.keyboardControlTextBrowser, 2, 0, 1, 3)
        self.verticalLayout.addWidget(self.controlGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 39))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.enginesPowerSlider.valueChanged['int'].connect(self.enginesPowerlcdNumber.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contrôleur du robot"))
        self.connectionStateLabel.setText(_translate("MainWindow", "Connexion au robot"))
        self.connectionPushButton.setText(_translate("MainWindow", "Déconnecté"))
        self.stateGroupBox.setTitle(_translate("MainWindow", "Etat"))
        self.distancesLabel.setText(_translate("MainWindow", "Distances"))
        self.distancesLineEdit.setText(_translate("MainWindow", "|0.00|0.00|0.00|0.00|0.00|0.00|0.00|"))
        self.dataCountLabel.setText(_translate("MainWindow", "Nombre de données"))
        self.temperatureLabel.setText(_translate("MainWindow", "Température de l\'environnement"))
        self.directionLabel.setText(_translate("MainWindow", "Direction"))
        self.directionLineEdit.setText(_translate("MainWindow", "Aucune"))
        self.navigationGroupBox.setTitle(_translate("MainWindow", "Navigation et capture"))
        self.enableCapturePushButton.setText(_translate("MainWindow", "Activer la capture"))
        self.navigationPushButton.setText(_translate("MainWindow", "Démarrer la navigation"))
        self.controlGroupBox.setTitle(_translate("MainWindow", "Commandes"))
        self.enginesPowerLabel.setText(_translate("MainWindow", "Puissance des moteurs"))
        self.forwardPushButton.setText(_translate("MainWindow", "Avant"))
        self.backwardPushButton.setText(_translate("MainWindow", "Arrière"))
        self.rightPushButton.setText(_translate("MainWindow", "Droite"))
        self.leftPushButton.setText(_translate("MainWindow", "Gauche"))
        self.keyboardControlTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Contrôle avec clavier :</p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Flèches : mouvement.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pages : puissance des moteurs.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">C : capture.</li></ul></body></html>"))

