# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/DistancesCarRemoteControler.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 682)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stateGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.stateGroupBox.setObjectName("stateGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stateGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connectionStateLabel = QtWidgets.QLabel(self.stateGroupBox)
        self.connectionStateLabel.setObjectName("connectionStateLabel")
        self.horizontalLayout.addWidget(self.connectionStateLabel)
        self.connectionPushButton = QtWidgets.QPushButton(self.stateGroupBox)
        self.connectionPushButton.setObjectName("connectionPushButton")
        self.horizontalLayout.addWidget(self.connectionPushButton)
        self.verticalLayout.addWidget(self.stateGroupBox)
        self.navigationGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.navigationGroupBox.setEnabled(False)
        self.navigationGroupBox.setObjectName("navigationGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.navigationGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.distancesLabel = QtWidgets.QLabel(self.navigationGroupBox)
        self.distancesLabel.setObjectName("distancesLabel")
        self.gridLayout_3.addWidget(self.distancesLabel, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.leftDistanceLcdNumber = QtWidgets.QLCDNumber(self.navigationGroupBox)
        self.leftDistanceLcdNumber.setSmallDecimalPoint(False)
        self.leftDistanceLcdNumber.setObjectName("leftDistanceLcdNumber")
        self.gridLayout_2.addWidget(self.leftDistanceLcdNumber, 0, 0, 1, 1)
        self.forwardDistanceLcdNumber = QtWidgets.QLCDNumber(self.navigationGroupBox)
        self.forwardDistanceLcdNumber.setObjectName("forwardDistanceLcdNumber")
        self.gridLayout_2.addWidget(self.forwardDistanceLcdNumber, 0, 1, 1, 1)
        self.rightDistanceLcdNumber = QtWidgets.QLCDNumber(self.navigationGroupBox)
        self.rightDistanceLcdNumber.setObjectName("rightDistanceLcdNumber")
        self.gridLayout_2.addWidget(self.rightDistanceLcdNumber, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.navigationPushButton = QtWidgets.QPushButton(self.navigationGroupBox)
        self.navigationPushButton.setCheckable(True)
        self.navigationPushButton.setObjectName("navigationPushButton")
        self.gridLayout_3.addWidget(self.navigationPushButton, 2, 0, 1, 2)
        self.enableCapturePushButton = QtWidgets.QPushButton(self.navigationGroupBox)
        self.enableCapturePushButton.setCheckable(True)
        self.enableCapturePushButton.setObjectName("enableCapturePushButton")
        self.gridLayout_3.addWidget(self.enableCapturePushButton, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.navigationGroupBox)
        self.controlGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.controlGroupBox.setEnabled(False)
        self.controlGroupBox.setObjectName("controlGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.controlGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.enginesPowerLabel = QtWidgets.QLabel(self.controlGroupBox)
        self.enginesPowerLabel.setObjectName("enginesPowerLabel")
        self.gridLayout_4.addWidget(self.enginesPowerLabel, 0, 0, 1, 1)
        self.enginesPowerSlider = QtWidgets.QSlider(self.controlGroupBox)
        self.enginesPowerSlider.setMaximum(255)
        self.enginesPowerSlider.setPageStep(25)
        self.enginesPowerSlider.setProperty("value", 127)
        self.enginesPowerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.enginesPowerSlider.setObjectName("enginesPowerSlider")
        self.gridLayout_4.addWidget(self.enginesPowerSlider, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.forwardPushButton = QtWidgets.QPushButton(self.controlGroupBox)
        self.forwardPushButton.setObjectName("forwardPushButton")
        self.gridLayout.addWidget(self.forwardPushButton, 0, 1, 1, 1)
        self.backwardPushButton = QtWidgets.QPushButton(self.controlGroupBox)
        self.backwardPushButton.setObjectName("backwardPushButton")
        self.gridLayout.addWidget(self.backwardPushButton, 2, 1, 1, 1)
        self.rightPushButton = QtWidgets.QPushButton(self.controlGroupBox)
        self.rightPushButton.setObjectName("rightPushButton")
        self.gridLayout.addWidget(self.rightPushButton, 1, 2, 1, 1)
        self.leftPushButton = QtWidgets.QPushButton(self.controlGroupBox)
        self.leftPushButton.setObjectName("leftPushButton")
        self.gridLayout.addWidget(self.leftPushButton, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.keyboardControlPlainTextEdit = QtWidgets.QPlainTextEdit(self.controlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyboardControlPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.keyboardControlPlainTextEdit.setSizePolicy(sizePolicy)
        self.keyboardControlPlainTextEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.keyboardControlPlainTextEdit.setReadOnly(True)
        self.keyboardControlPlainTextEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.keyboardControlPlainTextEdit.setObjectName("keyboardControlPlainTextEdit")
        self.gridLayout_4.addWidget(self.keyboardControlPlainTextEdit, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.controlGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 39))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contrôleur du robot"))
        self.stateGroupBox.setTitle(_translate("MainWindow", "Etat"))
        self.connectionStateLabel.setText(_translate("MainWindow", "Connexion au robot"))
        self.connectionPushButton.setText(_translate("MainWindow", "Déconnecté"))
        self.navigationGroupBox.setTitle(_translate("MainWindow", "Navigation et capture"))
        self.distancesLabel.setText(_translate("MainWindow", "Distances"))
        self.navigationPushButton.setText(_translate("MainWindow", "Démarrer la navigation"))
        self.enableCapturePushButton.setText(_translate("MainWindow", "Activer la capture"))
        self.controlGroupBox.setTitle(_translate("MainWindow", "Commandes"))
        self.enginesPowerLabel.setText(_translate("MainWindow", "Puissance des moteurs"))
        self.forwardPushButton.setText(_translate("MainWindow", "Avant"))
        self.backwardPushButton.setText(_translate("MainWindow", "Arrière"))
        self.rightPushButton.setText(_translate("MainWindow", "Droite"))
        self.leftPushButton.setText(_translate("MainWindow", "Gauche"))
        self.keyboardControlPlainTextEdit.setPlaceholderText(_translate("MainWindow", "Contrôle avec clavier"))

